"""
Task service for business logic and workflow management.
"""

from datetime import UTC, datetime

from enums import TaskStatus
from models import Task, TaskCreate, TaskSummary, TaskUpdate
from repositories.task_repo import TaskRepository


class TaskService:
    """
    Service layer for task management business logic.

    Responsibilities:
    - Validate task existence
    - Enforce status transitions
    - Coordinate repository operations
    - Apply business rules
    """

    def __init__(self, repository: TaskRepository) -> None:
        """
        Initialize the task service.

        Args:
            repository: Task repository implementation
        """
        self.repository = repository

    @staticmethod
    def _ensure_enum_status(status: TaskStatus | str) -> TaskStatus:
        """
        Ensure status is a TaskStatus enum.

        Args:
            status: Status as enum or string

        Returns:
            TaskStatus enum
        """
        if isinstance(status, TaskStatus):
            return status
        return TaskStatus(status)

    def add(
        self,
        title: str,
        description: str | None = None,
        status: TaskStatus | None = None,
    ) -> Task:
        """
        Add a new task.

        Args:
            title: Task title (required, non-empty)
            description: Optional task description
            status: Optional initial status (defaults to BACKLOG)

        Returns:
            Newly created task with auto-generated ID

        Raises:
            ValidationError: If TaskCreate validation fails
        """
        # Use TaskCreate schema for input validation
        task_create = TaskCreate(
            title=title, description=description, status=status or TaskStatus.BACKLOG
        )

        # Convert to Task model with ID and timestamps
        # ID will be auto-generated by repository
        task = Task(
            id=1,  # Temporary ID, will be replaced by repository
            title=task_create.title,
            description=task_create.description,
            status=task_create.status,
            created_at=datetime.now(tz=UTC),
            updated_at=datetime.now(tz=UTC),
        )

        return self.repository.add(task)

    def list_all(self) -> list[Task]:
        """
        List all tasks.

        Returns:
            List of all tasks
        """
        return self.repository.list_all()

    def list_by_status(self, status: TaskStatus) -> list[Task]:
        """
        List tasks filtered by status.

        Args:
            status: Status to filter by

        Returns:
            List of tasks with the specified status
        """
        tasks = self.repository.list_all()

        return [task for task in tasks if task.status == status]

    def get(self, task_id: int) -> Task:
        """
        Get a task by ID.

        Args:
            task_id: Task ID to retrieve

        Returns:
            Task if found

        Raises:
            ValueError: If task not found
        """
        task = self.repository.get_by_id(task_id)
        if task is None:
            raise ValueError(f"Task with ID {task_id} not found")
        return task

    def update(
        self,
        task_id: int,
        title: str | None = None,
        description: str | None = None,
        status: TaskStatus | None = None,
    ) -> Task:
        """
        Update a task's fields.

        Args:
            task_id: ID of task to update
            title: New title (optional)
            description: New description (optional)
            status: New status (optional, must be valid transition)

        Returns:
            Updated task

        Raises:
            ValueError: If task not found or status transition is invalid
            ValidationError: If TaskUpdate validation fails
        """
        # Get existing task
        existing_task = self.get(task_id)

        # Use TaskUpdate schema for validation
        task_update = TaskUpdate(title=title, description=description, status=status)

        # Get update data (only non-None values)
        update_data = task_update.model_dump(exclude_none=True)

        # Validate status transition if status is being updated
        if "status" in update_data:
            new_status = update_data["status"]
            # Ensure both statuses are enums for comparison
            existing_status = self._ensure_enum_status(existing_task.status)
            new_status_enum = self._ensure_enum_status(new_status)

            # Use enum's transition validation
            if not existing_status.can_transition_to(new_status_enum):
                # Use enum's error message generator
                error_msg = existing_status.get_transition_error_message(
                    new_status_enum
                )
                raise ValueError(error_msg)

        # Create updated task with new values merged with existing
        updated_task = Task(
            id=task_id,
            title=update_data.get("title", existing_task.title),
            description=update_data.get("description", existing_task.description),
            status=update_data.get("status", existing_task.status),
            created_at=existing_task.created_at,
            updated_at=datetime.now(tz=UTC),
        )

        result = self.repository.update(updated_task)
        if result is None:
            raise ValueError(f"Failed to update task with ID {task_id}")

        return result

    def mark_as_done(self, task_id: int) -> Task:
        """
        Mark a task as DONE.

        Args:
            task_id: ID of task to mark as done

        Returns:
            Updated task

        Raises:
            ValueError: If task not found, already done, or invalid transition
        """
        existing_task = self.get(task_id)

        # Ensure status is enum
        status = self._ensure_enum_status(existing_task.status)

        # Check if already done using enum property
        if status.is_final:
            raise ValueError(f"Task {task_id} is already marked as DONE")

        # Validate transition to DONE using enum method
        if not status.can_transition_to(TaskStatus.DONE):
            error_msg = status.get_transition_error_message(TaskStatus.DONE)
            raise ValueError(error_msg)

        return self.update(task_id, status=TaskStatus.DONE)

    def delete(self, task_id: int) -> bool:
        """
        Delete a task by ID.

        Args:
            task_id: ID of task to delete

        Returns:
            True if deleted successfully

        Raises:
            ValueError: If task not found
        """
        # Verify task exists
        self.get(task_id)

        result = self.repository.delete(task_id)
        if not result:
            raise ValueError(f"Failed to delete task with ID {task_id}")

        return result

    def get_summary(self) -> TaskSummary:
        """
        Get task summary statistics.

        Returns:
            TaskSummary model containing:
            - total: Total number of tasks
            - backlog: Number of BACKLOG tasks
            - todo: Number of TODO tasks
            - in_progress: Number of IN_PROGRESS tasks
            - testing: Number of TESTING tasks
            - done: Number of DONE tasks
            - completion_percentage: Percentage of completed tasks
            - active_tasks: Number of active tasks (TODO, IN_PROGRESS, TESTING)
            - pending_tasks: Number of pending tasks (BACKLOG, TODO)
        """
        tasks = self.repository.list_all()
        total = len(tasks)

        if total == 0:
            return TaskSummary(
                total=0,
                backlog=0,
                todo=0,
                in_progress=0,
                testing=0,
                done=0,
                active_tasks=0,
                pending_tasks=0,
                completion_percentage=0.0,
            )

        # Count tasks by status (ensure enum comparison)
        status_counts = {
            "backlog": sum(
                1
                for t in tasks
                if self._ensure_enum_status(t.status) == TaskStatus.BACKLOG
            ),
            "todo": sum(
                1
                for t in tasks
                if self._ensure_enum_status(t.status) == TaskStatus.TODO
            ),
            "in_progress": sum(
                1
                for t in tasks
                if self._ensure_enum_status(t.status) == TaskStatus.IN_PROGRESS
            ),
            "testing": sum(
                1
                for t in tasks
                if self._ensure_enum_status(t.status) == TaskStatus.TESTING
            ),
            "done": sum(
                1
                for t in tasks
                if self._ensure_enum_status(t.status) == TaskStatus.DONE
            ),
        }

        # Use enum properties for computed counts
        active_tasks = sum(
            1 for t in tasks if self._ensure_enum_status(t.status).is_active
        )
        pending_tasks = sum(
            1 for t in tasks if self._ensure_enum_status(t.status).is_pending
        )

        completion_percentage = (status_counts["done"] / total) * 100

        return TaskSummary(
            total=total,
            **status_counts,
            active_tasks=active_tasks,
            pending_tasks=pending_tasks,
            completion_percentage=completion_percentage,
        )
