"""
Task Service Module

This module contains the business logic for task management.
"""

from datetime import datetime

from ..models import Task, TaskStatus
from ..storage.base import TaskRepository


class TaskService:
    """
    Service layer for task management business logic.

    Responsibilities:
    - Validate task existence
    - Enforce status transitions
    - Coordinate repository operations
    - Apply business rules
    """

    # Define valid status transitions (workflow states)
    VALID_TRANSITIONS = {
        TaskStatus.BACKLOG: [TaskStatus.TODO, TaskStatus.IN_PROGRESS],
        TaskStatus.TODO: [TaskStatus.BACKLOG, TaskStatus.IN_PROGRESS],
        TaskStatus.IN_PROGRESS: [TaskStatus.TODO, TaskStatus.TESTING, TaskStatus.DONE],
        TaskStatus.TESTING: [TaskStatus.IN_PROGRESS, TaskStatus.DONE],
        TaskStatus.DONE: [],  # Cannot transition from DONE
    }

    def __init__(self, repository: TaskRepository) -> None:
        """
        Initialize the task service.

        Args:
            repository: Task repository implementation
        """
        self.repository = repository

    def add_task(self, title: str, description: str | None = None) -> Task:
        """
        Add a new task with default status BACKLOG.

        Args:
            title: Task title (required, non-empty)
            description: Optional task description

        Returns:
            Newly created task with auto-generated ID

        Raises:
            ValueError: If title is empty
        """
        if not title or not title.strip():
            raise ValueError("Task title cannot be empty")

        # Create task with default status
        task = Task(
            id=0,  # Will be auto-generated by repository
            title=title.strip(),
            description=description.strip() if description else None,
            status=TaskStatus.BACKLOG,
            created_at=datetime.now(),
            updated_at=datetime.now(),
        )

        return self.repository.add(task)

    def list_tasks(self, status: TaskStatus | None = None) -> list[Task]:
        """
        List all tasks, optionally filtered by status.

        Args:
            status: Optional status filter

        Returns:
            List of tasks matching the filter
        """
        tasks = self.repository.list()

        if status is not None:
            tasks = [task for task in tasks if task.status == status]

        return tasks

    def get_task(self, task_id: int) -> Task:
        """
        Get a task by ID.

        Args:
            task_id: Task ID to retrieve

        Returns:
            Task if found

        Raises:
            ValueError: If task not found
        """
        task = self.repository.get_by_id(task_id)
        if task is None:
            raise ValueError(f"Task with ID {task_id} not found")
        return task

    def update_task(
        self,
        task_id: int,
        title: str | None = None,
        description: str | None = None,
        status: TaskStatus | None = None,
    ) -> Task:
        """
        Update a task's fields.

        Args:
            task_id: ID of task to update
            title: New title (optional)
            description: New description (optional)
            status: New status (optional, must be valid transition)

        Returns:
            Updated task

        Raises:
            ValueError: If task not found, title is empty, or
                        status transition is invalid
        """
        # Get existing task
        existing_task = self.get_task(task_id)

        # Validate title if provided
        if title is not None:
            if not title or not title.strip():
                raise ValueError("Task title cannot be empty")
            title = title.strip()
        else:
            title = existing_task.title

        # Handle description
        if description is not None:
            description = description.strip() if description else None
        else:
            description = existing_task.description

        # Validate status transition if provided
        if status is not None:
            if not self._is_valid_transition(existing_task.status, status):
                raise ValueError(
                    "Invalid status transition from "
                    f"{existing_task.status.value} to {status.value}"
                )
        else:
            status = existing_task.status

        # Create updated task
        updated_task = Task(
            id=task_id,
            title=title,
            description=description,
            status=status,
            created_at=existing_task.created_at,
            updated_at=datetime.now(),
        )

        result = self.repository.update(updated_task)
        if result is None:
            raise ValueError(f"Failed to update task with ID {task_id}")

        return result

    def mark_as_done(self, task_id: int) -> Task:
        """
        Mark a task as DONE.

        Args:
            task_id: ID of task to mark as done

        Returns:
            Updated task

        Raises:
            ValueError: If task not found or already done
        """
        existing_task = self.get_task(task_id)

        # Check if already done
        if existing_task.status == TaskStatus.DONE:
            raise ValueError(f"Task {task_id} is already marked as DONE")

        # Validate transition to DONE
        if not self._is_valid_transition(existing_task.status, TaskStatus.DONE):
            valid_transitions_str = ", ".join(
                s.value for s in self.VALID_TRANSITIONS[existing_task.status]
            )
            raise ValueError(
                f"Cannot mark task as DONE from status {existing_task.status.value}. "
                f"Valid transitions: {valid_transitions_str}"
            )

        return self.update_task(task_id, status=TaskStatus.DONE)

    def delete_task(self, task_id: int) -> bool:
        """
        Delete a task by ID.

        Args:
            task_id: ID of task to delete

        Returns:
            True if deleted successfully

        Raises:
            ValueError: If task not found
        """
        # Verify task exists
        self.get_task(task_id)

        result = self.repository.delete(task_id)
        if not result:
            raise ValueError(f"Failed to delete task with ID {task_id}")

        return result

    def get_summary(self) -> dict[str, int | float]:
        """
        Get task summary statistics.

        Returns:
            Dictionary containing:
            - total: Total number of tasks
            - backlog: Number of BACKLOG tasks
            - todo: Number of TODO tasks
            - in_progress: Number of IN_PROGRESS tasks
            - testing: Number of TESTING tasks
            - done: Number of DONE tasks
            - completion_percentage: Percentage of completed tasks
        """
        tasks = self.repository.list()
        total = len(tasks)

        if total == 0:
            return {
                "total": 0,
                "backlog": 0,
                "todo": 0,
                "in_progress": 0,
                "testing": 0,
                "done": 0,
                "completion_percentage": 0.0,
            }

        # Count tasks by status
        status_counts = {
            "backlog": sum(1 for t in tasks if t.status == TaskStatus.BACKLOG),
            "todo": sum(1 for t in tasks if t.status == TaskStatus.TODO),
            "in_progress": sum(1 for t in tasks if t.status == TaskStatus.IN_PROGRESS),
            "testing": sum(1 for t in tasks if t.status == TaskStatus.TESTING),
            "done": sum(1 for t in tasks if t.status == TaskStatus.DONE),
        }

        completion_percentage = (status_counts["done"] / total) * 100

        return {
            "total": total,
            **status_counts,
            "completion_percentage": round(completion_percentage, 2),
        }

    def _is_valid_transition(
        self, current_status: TaskStatus, new_status: TaskStatus
    ) -> bool:
        """
        Check if a status transition is valid.

        Args:
            current_status: Current task status
            new_status: Desired new status

        Returns:
            True if transition is valid, False otherwise
        """
        # Same status is always valid (no-op)
        if current_status == new_status:
            return True

        # Check if new_status is in the list of valid transitions
        valid_next_statuses = self.VALID_TRANSITIONS.get(current_status, [])
        return new_status in valid_next_statuses
