"""Auth module constants — JWT settings and error codes."""

# JWT configuration keys (actual values come from src.config.settings)
JWT_TOKEN_TYPE = "bearer"

# Error codes
ERR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
ERR_EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
ERR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
ERR_TOKEN_INVALID = "TOKEN_INVALID"
ERR_TOKEN_REVOKED = "TOKEN_REVOKED"
ERR_INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
