"""Auth module constants."""

# Token types
ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"

# Error codes
ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
ERROR_TOKEN_REVOKED = "TOKEN_REVOKED"
ERROR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
ERROR_INVALID_TOKEN = "INVALID_TOKEN"
ERROR_INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE"
