"""
Task service for business logic and workflow management.
"""

from datetime import datetime

from ..models import Task, TaskCreate, TaskStatus, TaskUpdate
from ..storage.base import BaseTaskRepository


class TaskService:
    """
    Service layer for task management business logic.

    Responsibilities:
    - Validate task existence
    - Enforce status transitions
    - Coordinate repository operations
    - Apply business rules
    """

    # Define valid status transitions (workflow states)
    VALID_TRANSITIONS = {
        TaskStatus.BACKLOG: [TaskStatus.TODO, TaskStatus.IN_PROGRESS],
        TaskStatus.TODO: [TaskStatus.BACKLOG, TaskStatus.IN_PROGRESS],
        TaskStatus.IN_PROGRESS: [TaskStatus.TODO, TaskStatus.TESTING, TaskStatus.DONE],
        TaskStatus.TESTING: [TaskStatus.IN_PROGRESS, TaskStatus.DONE],
        TaskStatus.DONE: [],  # Cannot transition from DONE
    }

    def __init__(self, repository: BaseTaskRepository) -> None:
        """
        Initialize the task service.

        Args:
            repository: Task repository implementation
        """
        self.repository = repository

    def add(
        self,
        title: str,
        description: str | None = None,
        status: TaskStatus | None = None,
    ) -> Task:
        """
        Add a new task.

        Args:
            title: Task title (required, non-empty)
            description: Optional task description
            status: Optional initial status (defaults to BACKLOG)

        Returns:
            Newly created task with auto-generated ID

        Raises:
            ValidationError: If TaskCreate validation fails
        """
        # Use TaskCreate schema for input validation
        task_create = TaskCreate(
            title=title, description=description, status=status or TaskStatus.BACKLOG
        )

        # Convert to Task model with ID and timestamps
        # ID will be auto-generated by repository
        task = Task(
            id=1,  # Temporary ID, will be replaced by repository
            title=task_create.title,
            description=task_create.description,
            status=task_create.status,
            created_at=datetime.now(),
            updated_at=datetime.now(),
        )

        return self.repository.add(task)

    def list_all(self) -> list[Task]:
        """
        List all tasks.

        Returns:
            List of all tasks
        """
        return self.repository.list_all()

    def list_by_status(self, status: TaskStatus) -> list[Task]:
        """
        List tasks filtered by status.

        Args:
            status: Status to filter by

        Returns:
            List of tasks with the specified status
        """
        tasks = self.repository.list_all()
        return [task for task in tasks if task.status == status]

    def get(self, task_id: int) -> Task:
        """
        Get a task by ID.

        Args:
            task_id: Task ID to retrieve

        Returns:
            Task if found

        Raises:
            ValueError: If task not found
        """
        task = self.repository.get_by_id(task_id)
        if task is None:
            raise ValueError(f"Task with ID {task_id} not found")
        return task

    def update(
        self,
        task_id: int,
        title: str | None = None,
        description: str | None = None,
        status: TaskStatus | None = None,
    ) -> Task:
        """
        Update a task's fields.

        Args:
            task_id: ID of task to update
            title: New title (optional)
            description: New description (optional)
            status: New status (optional, must be valid transition)

        Returns:
            Updated task

        Raises:
            ValueError: If task not found or status transition is invalid
            ValidationError: If TaskUpdate validation fails
        """
        # Get existing task
        existing_task = self.get(task_id)

        # Use TaskUpdate schema for validation
        task_update = TaskUpdate(title=title, description=description, status=status)

        # Get update data (only non-None values)
        update_data = task_update.model_dump(exclude_none=True)

        # Validate status transition if status is being updated
        if "status" in update_data:
            new_status = update_data["status"]
            if not self._is_valid_transition(existing_task.status, new_status):
                raise ValueError(
                    f"Invalid status transition from "
                    f"{existing_task.status.value} to {new_status.value}"
                )

        # Create updated task with new values merged with existing
        updated_task = Task(
            id=task_id,
            title=update_data.get("title", existing_task.title),
            description=update_data.get("description", existing_task.description),
            status=update_data.get("status", existing_task.status),
            created_at=existing_task.created_at,
            updated_at=datetime.now(),
        )

        result = self.repository.update(updated_task)
        if result is None:
            raise ValueError(f"Failed to update task with ID {task_id}")

        return result

    def mark_as_done(self, task_id: int) -> Task:
        """
        Mark a task as DONE.

        Args:
            task_id: ID of task to mark as done

        Returns:
            Updated task

        Raises:
            ValueError: If task not found, already done, or invalid transition
        """
        existing_task = self.get(task_id)

        # Check if already done
        if existing_task.status == TaskStatus.DONE:
            raise ValueError(f"Task {task_id} is already marked as DONE")

        # Validate transition to DONE
        if not self._is_valid_transition(existing_task.status, TaskStatus.DONE):
            valid_transitions_str = ", ".join(
                s.value for s in self.VALID_TRANSITIONS[existing_task.status]
            )
            raise ValueError(
                f"Cannot mark task as DONE from status {existing_task.status.value}. "
                f"Valid transitions: {valid_transitions_str}"
            )

        return self.update(task_id, status=TaskStatus.DONE)

    def delete(self, task_id: int) -> bool:
        """
        Delete a task by ID.

        Args:
            task_id: ID of task to delete

        Returns:
            True if deleted successfully

        Raises:
            ValueError: If task not found
        """
        # Verify task exists
        self.get(task_id)

        result = self.repository.delete(task_id)
        if not result:
            raise ValueError(f"Failed to delete task with ID {task_id}")

        return result

    def get_summary(self) -> dict[str, int | float]:
        """
        Get task summary statistics.

        Returns:
            Dictionary containing:
            - total: Total number of tasks
            - backlog: Number of BACKLOG tasks
            - todo: Number of TODO tasks
            - in_progress: Number of IN_PROGRESS tasks
            - testing: Number of TESTING tasks
            - done: Number of DONE tasks
            - completion_percentage: Percentage of completed tasks
        """
        tasks = self.repository.list_all()
        total = len(tasks)

        if total == 0:
            return {
                "total": 0,
                "backlog": 0,
                "todo": 0,
                "in_progress": 0,
                "testing": 0,
                "done": 0,
                "completion_percentage": 0.0,
            }

        # Count tasks by status
        status_counts = {
            "backlog": sum(1 for t in tasks if t.status == TaskStatus.BACKLOG),
            "todo": sum(1 for t in tasks if t.status == TaskStatus.TODO),
            "in_progress": sum(1 for t in tasks if t.status == TaskStatus.IN_PROGRESS),
            "testing": sum(1 for t in tasks if t.status == TaskStatus.TESTING),
            "done": sum(1 for t in tasks if t.status == TaskStatus.DONE),
        }

        completion_percentage = (status_counts["done"] / total) * 100

        return {
            "total": total,
            **status_counts,
            "completion_percentage": round(completion_percentage, 2),
        }

    def _is_valid_transition(
        self, current_status: TaskStatus, new_status: TaskStatus
    ) -> bool:
        """
        Check if a status transition is valid.

        Args:
            current_status: Current task status
            new_status: Desired new status

        Returns:
            True if transition is valid, False otherwise
        """
        # Same status is always valid (no-op)
        if current_status == new_status:
            return True

        # Check if new_status is in the list of valid transitions
        valid_next_statuses = self.VALID_TRANSITIONS.get(current_status, [])
        return new_status in valid_next_statuses
